---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
    customize:
      memory: 1024
  run_list:
  - recipe[apt::default]

suites:
- name: default
  run_list:
  - recipe[cf-jenkins]
  attributes:
    rubies:
      list:
      - 'ruby 1.9.3-p484'
      install_bundler: true
    chruby_install:
      default_ruby: '1.9.3-p484'
      auto: false
    selfsigned_certificate:
      destination: /usr/var/ssl/certs/
      sslpassphrase: changeme
      country: CO
      state: ST
      city: CI
      orga: OR
      depart: DE
      cn: CN
      email: EMAIL
    cf_jenkins:
      ssh_known_hosts: []
      jobs:
      - name: dummy_job
        build_vars:
          build_repo: https://github.com/cloudfoundry/tac.git
          build_repo_branch: master
          build_shell_command: |
            #!/bin/bash -l # required to load /etc/profile.d/gvm.sh

            env | sort

            type gvm # this should be a function, loaded by /etc/profile.d/gvm.sh

            if ! gvm use 1.2; then
              echo "Wrong Go version or GVM not installed."
              exit 1
            fi

            if ! chruby 1.9.3; then
              echo "Wrong Ruby version or chruby not installed."
              exit 1
            fi

            echo "All is well."
            exit 0
