---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt::default]

suites:
- name: default
  run_list:
  - recipe[cf-jenkins]
  attributes:
    cf_jenkins:
      ssh_known_hosts: []
      jobs: []
    rubies:
      list: []
    selfsigned_certificate:
      destination: /usr/var/ssl/certs/
      sslpassphrase: changeme
      country: CO
      state: ST
      city: CI
      orga: OR
      depart: DE
      cn: CN
      email: EMAIL
