name    'cf-jenkins'
version '0.0.2'

depends 'apt'
depends 'aws'
depends 'chef_handler'
depends 'rubies'
depends 'chruby_install'
depends 'jenkins'
depends 'java'
depends 'selfsigned_certificate'
depends 'nginx'
